name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  camera: ^0.10.0+3
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.4.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.4.3
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/animations/
    - assets/logos/
