name: chat_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.2.2
  camera: ^0.10.0+4
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.5
  emoji_picker_flutter: ^1.5.0
  extended_text_field: ^10.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.1.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.4.3
  media_picker_widget: ^0.0.9
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
  video_player: ^2.4.7
  flutter_native_splash: ^2.2.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_chitchat.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/logo_chitchat.png"

flutter_native_splash:
  color: "#fae179"
  image: assets/logos/logo_chitchat_1680.png

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/animations/
    - assets/logos/
