name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.5
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^3.0.1
  lottie: ^1.4.3
  animated_splash_screen: ^1.3.0

  
  # State Manager
  flutter_bloc: ^8.1.1
  provider: ^6.0.0
  get: ^4.6.5
  
  #camera
  camera: ^0.10.0+3
  path: ^1.8.2
  path_provider: ^2.0.11
  
  #Gallery
  image_picker: ^0.8.5+3
  
  # Restful API 
  http: ^0.13.5

  # Database
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/animations/
    - assets/logos/
